[project]
name = "canvasgradeanalyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.2.0",
    "polars>=1.32.0",
    "streamlit>=1.47.1",
]
